export const Cards = [
  { name: 'Ace of Spades', shortform: 'AS' },
  { name: '2 of Spades', shortform: '2S' },
  { name: '3 of Spades', shortform: '3S' },
  { name: '4 of Spades', shortform: '4S' },
  { name: '5 of Spades', shortform: '5S' },
  { name: '6 of Spades', shortform: '6S' },
  { name: '7 of Spades', shortform: '7S' },
  { name: '8 of Spades', shortform: '8S' },
  { name: '9 of Spades', shortform: '9S' },
  { name: '10 of Spades', shortform: '10S' },
  { name: 'Jack of Spades', shortform: 'JS' },
  { name: 'Queen of Spades', shortform: 'QS' },
  { name: 'King of Spades', shortform: 'KS' },

  { name: 'Ace of Hearts', shortform: 'AH' },
  { name: '2 of Hearts', shortform: '2H' },
  { name: '3 of Hearts', shortform: '3H' },
  { name: '4 of Hearts', shortform: '4H' },
  { name: '5 of Hearts', shortform: '5H' },
  { name: '6 of Hearts', shortform: '6H' },
  { name: '7 of Hearts', shortform: '7H' },
  { name: '8 of Hearts', shortform: '8H' },
  { name: '9 of Hearts', shortform: '9H' },
  { name: '10 of Hearts', shortform: '10H' },
  { name: 'Jack of Hearts', shortform: 'JH' },
  { name: 'Queen of Hearts', shortform: 'QH' },
  { name: 'King of Hearts', shortform: 'KH' },

  { name: 'Ace of Diamonds', shortform: 'AD' },
  { name: '2 of Diamonds', shortform: '2D' },
  { name: '3 of Diamonds', shortform: '3D' },
  { name: '4 of Diamonds', shortform: '4D' },
  { name: '5 of Diamonds', shortform: '5D' },
  { name: '6 of Diamonds', shortform: '6D' },
  { name: '7 of Diamonds', shortform: '7D' },
  { name: '8 of Diamonds', shortform: '8D' },
  { name: '9 of Diamonds', shortform: '9D' },
  { name: '10 of Diamonds', shortform: '10D' },
  { name: 'Jack of Diamonds', shortform: 'JD' },
  { name: 'Queen of Diamonds', shortform: 'QD' },
  { name: 'King of Diamonds', shortform: 'KD' },

  { name: 'Ace of Clubs', shortform: 'AC' },
  { name: '2 of Clubs', shortform: '2C' },
  { name: '3 of Clubs', shortform: '3C' },
  { name: '4 of Clubs', shortform: '4C' },
  { name: '5 of Clubs', shortform: '5C' },
  { name: '6 of Clubs', shortform: '6C' },
  { name: '7 of Clubs', shortform: '7C' },
  { name: '8 of Clubs', shortform: '8C' },
  { name: '9 of Clubs', shortform: '9C' },
  { name: '10 of Clubs', shortform: '10C' },
  { name: 'Jack of Clubs', shortform: 'JC' },
  { name: 'Queen of Clubs', shortform: 'QC' },
  { name: 'King of Clubs', shortform: 'KC' },
]
